# Generated by Django 3.2.12 on 2024-03-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageUrl',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
