# Generated by Django 3.2.12 on 2024-06-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.CharField(default=' ', max_length=140),
        ),
    ]
